### PR TITLE
Fix handling of reverse schemata

### PR DESCRIPTION
**Pull request by jsangmeister**
fixes the errors encountered in #75. May also fix https://github.com/OpenSlides-action-crew/openslides-backend-coordination/issues/75, please test @GabrielInTheWorld

### CODE REVIEW

**Comment by jsangmeister** [comment]
@normanjaeckel did you silenty accept or miss this? :D anyway, I would like your review on this. Is this right and you missed it when implementing reverse relations?

**Comment by normanjaeckel** [comment]
In lines 63 to 65 i switch the type so your change should not be required. But maybe there is a misstake and we have to use `self.type` and not `self.field.type`.

**Comment by jsangmeister** [comment]
Well, It didn't work before and now it works :D Maybe you want to look into it where the mistake lays? The relation handling is critical for the backend and I don't know enough about your code to debug this.

**Comment by normanjaeckel** [comment]
Do you have a test or test szenario for me for the error case?

**Pull request merged**
