### PR TITLE
Removed DummyAction

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by jsangmeister** [comment]
Why do you want to remove them? They are needed for the cascade deletion. Without them for example deleting an assignment with an associated poll (like in the exaple data) fails because it does not find a delete action for the poll and options. I would suggest to keep it in until all actions are implemented.

**Comment by normanjaeckel** [comment]
Ready to merge.

**Comment by jsangmeister** [comment]
Yes, it is a dummy action. You removed it in this PR. And it does work, I implemented the dummy actions specially for this. Only thing missing is a test for this, but I didn't think it was necessary to test dummy actions. -- And you are right, we should implement these, but until they are implemented, we NEED these dummy actions.

**Comment by FinnStutzenstein** [comment]
@jsangmeister Please provide a failing test proving your statement.

**Review by jsangmeister — APPROVED** [review]

**Comment by jsangmeister** [comment]
Mentioned issues should be fixed with #387. Must rebase

**Pull request merged**
