### PR TITLE
Add password to internal routes & differentiate internal actions

### LINKED ISSUE #1058: Implement authentication per secret for internal requests
see https://github.com/OpenSlides/openslides-backend/pull/1029#issuecomment-977884715

waiting for manage service to define said secret

### LINKED ISSUE #1096: Can not reach internal action in production mode
https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/action_handler.py#L207

Looks like I can not reach the internal action `organization.initial_import` in production mode.

### PR DESCRIPTION
**Pull request by jsangmeister**
fixes #1096 
fixes #1058

### CODE REVIEW

**Review by peb-adr — APPROVED** [review]
I can confirm the authorization on stack internal requests works now.

**Comment by jsangmeister** [comment]
Should I merge this or wait for more reviews?

**Review by normanjaeckel — APPROVED** [review]
Looks good but I have not tested this. Please merge and let's see ... ;-)

**Review by r-peschke — APPROVED** [review]

**Comment by normanjaeckel** [comment]
Merged together with https://github.com/OpenSlides/openslides-manage-service/pull/127

**Pull request merged**
