### PR TITLE
motion.set_state, -reset_state and follow_recommendation checked for correct number

### PR DESCRIPTION
**Pull request by r-peschke**
Just small changes to see the "privacy" of some methods and the used "set_state"-value

### CODE REVIEW

**Comment by r-peschke** [comment]
resolves OpenSlides/openslides-backend-coordination#105

**Review by jsangmeister — APPROVED** [review]

**Review by FinnStutzenstein — CHANGES_REQUESTED** [review]
Please see https://github.com/OpenSlides/openslides-backend/issues/418

**Comment by r-peschke** [comment]
The actions (set_state, reset_state, follow_recommendation) execute set_number, which is covered by tests, see #418

**Comment by jsangmeister** [comment]
This should be good to go then. I'm gonna go ahead and merge it

**Pull request merged**
