### PR TITLE
Rename payload to action_data

### LINKED ISSUE #454: Rename payload to action_data
Splitup from #261

### PR DESCRIPTION
**Pull request by jsangmeister**
closes #454 

Forgot to add the renaming to #461, so adding that with this PR.

@all: Please consequently use the new wording:
- Payload: Everything that is sent from the client.
- PayloadElement: A single Element of this list which contains the name of the action and the ActionData.
- ActionData: The list of data that is supplied for a single action.
- Instance (Action data element, ...): May have different names, depending on the context. Most of the time it reflects an instance of a model (e.g. for CUD actions)

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Please also move the naming conventions here: https://github.com/OpenSlides/OpenSlides/wiki/Action-Service

**Review by FinnStutzenstein — APPROVED** [review]

**Review by r-peschke — APPROVED** [review]
Looks really good. Feel free and enjoy your **Brownie points**:-)

**Comment by jsangmeister** [comment]
> Please also move the naming conventions here: https://github.com/OpenSlides/OpenSlides/wiki/Action-Service

Done

**Comment by FinnStutzenstein** [comment]
Please resolve conflicts so it can be merged.

**Pull request merged**
