### PR TITLE
Update the sort actions to use arrays in data.

### PR DESCRIPTION
**Pull request by reiterl**
Try to fix https://github.com/OpenSlides-action-crew/openslides-backend-coordination/issues/57

### CODE REVIEW

**Comment by normanjaeckel** [comment]
I think this would only be a hotfix. What if the client sends more then one item inside the array? To do this properly we have to loop over the items of the array and create multiple results.

I really recommend that we do NOT change the behavior here and let the client send an object instead of an array. This would be cleaner at the moment and means no more work here.

@FinnStutzenstein ?

**Comment by jsangmeister** [comment]
Let's keep the discussion in https://github.com/OpenSlides-action-crew/openslides-backend-coordination/issues/57#issuecomment-701542581

**Comment by normanjaeckel** [comment]
I will care of this PR and merge it.

**Comment by normanjaeckel** [comment]
I adjusted the ActionPayload to be always an array of data. @reiterl Can you please fix the last tests here for two other actions that formerly required a dict? Then this PR can be merged.

**Comment by jsangmeister** [comment]
Doing that now so this is finally finished

**Pull request merged**
