### PR TITLE
Add permissions to motion_comment_section actions. Update tests

### PR DESCRIPTION
**Pull request by reiterl**

### CODE REVIEW

**Review by FinnStutzenstein — COMMENTED** [review]
OK, but see https://github.com/OpenSlides/openslides-backend/issues/609

**Review by jsangmeister — CHANGES_REQUESTED** [review]
See https://github.com/OpenSlides/openslides-backend/pull/603#discussion_r602177045

**Review by jsangmeister — APPROVED** [review]

**Review by jsangmeister — CHANGES_REQUESTED** [review]
Please change permission strings to the enum

**Review by jsangmeister — APPROVED** [review]
Whoops, just saw https://github.com/OpenSlides/openslides-backend/pull/603#discussion_r603213092...

**Pull request merged**
