### PR TITLE
Fixed decimal implementation

### PR DESCRIPTION
**Pull request by jsangmeister**
@FinnStutzenstein it's correct that decimals are always positive, right?

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
No, there are special values `-1` and `-2` for `votescast` and so on.

**Comment by jsangmeister** [comment]
Mmh, right. So the final regex would be `^-?(\d|[1-9]\d+)(\.\d{6})$` to support all needed numbers. Anything missing, before I need to create yet another PR for this? :D

**Comment by jsangmeister** [comment]
Or should I restrain negative numbers to just `-1` and `-2`? Then, it would be ^-1|-2|(\d|[1-9]\d+)(\.\d{6})$

**Comment by FinnStutzenstein** [comment]
> Or should I restrain negative numbers to just -1 and -2?

Would be enough for our use case, but then name the decimal field class something like `VotingDecimalFieldWithSpecialValues` so so ;)

Also: Currently OS3 accepts these numbers as floats since JS does not have a native decimal implementation.

**Comment by jsangmeister** [comment]
> Also: Currently OS3 accepts these numbers as floats since JS does not have a native decimal implementation.

What does this mean for OS4? Should we accept strings and floats?

**Comment by FinnStutzenstein** [comment]
Ok, only strings. We'll adapt the client

**Comment by jsangmeister** [comment]
Ok, final regex: ^-?(\d|[1-9]\d+)\.\d{6}$ (so all numbers with exactly 6 decimal places are accepted)

**Pull request merged**
