### PR TITLE
The authlib expects to get the endpoint without the url

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by jsangmeister** [comment]
The `AUTH_PATH` is overridden in the `docker-compose.dev.yml`. If I remove that entry, the auth cannot be reached anymore.

**Comment by FinnStutzenstein** [comment]
black formatted a lot of stuff; maybe there was an update. I rebuilt all containers so it might be possible.

**Comment by jsangmeister** [comment]
I guess you didn't rebase, black should automatically exluce the old integration tests to not have to deal with changes there in PRs.

**Comment by normanjaeckel** [comment]
Does the authlib library magically set HOST, PORT and PATH of the auth service? I think it should be configurable ...

**Comment by FinnStutzenstein** [comment]
> I think it should be configurable ...

It is, but the service does it (gets the variables from the env)

**Comment by FinnStutzenstein** [comment]
@jsangmeister Ok, should these changes be redone?

**Comment by jsangmeister** [comment]
> @jsangmeister Ok, should these changes be redone?

Na, it's ok, since these files shouldn't be used anymore. It just makes the PR more convoluted ^^ but it looks good, if you squash we can merge this.

**Comment by jsangmeister** [comment]
Done.

**Comment by normanjaeckel** [comment]
Please add the silently used environment variables to the README so that users of the openslides_backend know how to configure this service if they want to connect it via the authlib package to another instance of the auth service.

**Comment by FinnStutzenstein** [comment]
https://github.com/OpenSlides/openslides-backend/pull/301

**Pull request merged**
