### PR TITLE
Add explicit test for group meeting_ids for temporary users. Update t…

### PR DESCRIPTION
**Pull request by reiterl**
…he tests.

### CODE REVIEW

**Review by jsangmeister — APPROVED** [review]
Ah right, forgot that the equal fields check already caught this one. But double is better ;)

**Comment by reiterl** [comment]
Ralf has changed the place of the group_ids, so this pr is no longer useful.

**Comment by jsangmeister** [comment]
> Ralf has changed the place of the group_ids, so this pr is no longer useful.

What do you mean?

**Comment by reiterl** [comment]
Ah, talked with Ralf about it. I will merge this, after a rebase.

**Pull request merged**
