### PR TITLE
Add Decimal & Html field

### PR DESCRIPTION
**Pull request by jsangmeister**
Also add automatic html validation.

### CODE REVIEW

**Comment by jsangmeister** [comment]
Tag list and validation style copied from OS3.

**Comment by normanjaeckel** [comment]
Please wait with this PR until we have the new calculated models.py.

**Comment by normanjaeckel** [comment]
The easiest solution I think is to use two fields: HTMLStrictField and HTMLPermissiveField. Therefor we have to change the types in the new models.yml and adjust the `dev/generate_models.py` (all after #153 is merged).

If we need more flexibility we can do this later.

**Comment by jsangmeister** [comment]
Why do we generate the models now? I thought we agreed in our phone call that it's not necessary since we have most of the models finished already?

**Comment by jsangmeister** [comment]
> Please wait with this PR until we have the new calculated models.py.

Merging this now so it is available for client work. The changes you mentioned can also be done in your PR if needed.

**Pull request merged**
