### PR TITLE
Update count users for check against the limit of users. 

### PR DESCRIPTION
**Pull request by reiterl**
Draft version. In the first commit, I have moved the counting into one function and in the second commit I have implemented a possible(?) solution. As far as I understand this. 
Here some more time must be invested into the places where to check for limit of users. See user.update, groups,...

### CODE REVIEW

**Comment by r-peschke** [comment]
Actions, where a user will be added to the number of users:
- **unarchive a meeting**
- user.update/create: **adding to group, committee or orga-rights, activate an user**
- user.create:**create an user without giving him a group**
- **on data import not using the standard actions**
- **on saml/sso user addition**
- undelete actions on meeting, group, user, committee

@rrenkert @MSoeb @emanuelschuetze could you have a look on these, maybe there are more

**Review by reiterl — COMMENTED** [review]
Looks good. The orga management user is user/1.  So all cases there.
If we split the places of the limit check to a *different* issue, I approve this.
But I'm the creator of this pr, so I cannot approve this.

**Comment by jsangmeister** [comment]
I assume that since https://github.com/OpenSlides/openslides-backend/issues/1762 was changed this is not ready for review anymore?

**Comment by r-peschke** [comment]
> I assume that since #1762 was changed this is not ready for review anymore?

yes, the requirements changed

**Comment by jsangmeister** [comment]
Currently too complex to implement. Closing for now.

**Pull request closed without merging**
