### PR TITLE
Add calculated field poll/vote_count

### PR DESCRIPTION
**Pull request by ostcar**
This change is required for the autoupdate-service

See https://github.com/OpenSlides/openslides-vote-service/issues/16

### CODE REVIEW

**Comment by ostcar** [comment]
I don't understand why the test fail. Can someone of you fix this or tell me what to fix?

**Comment by reiterl** [comment]
Mmh, I think, the checksum problem is because you need to generate and commit the models.py too.
I will look at the forget_password test error.

**Comment by r-peschke** [comment]
> I don't understand why the test fail. Can someone of you fix this or tell me what to fix?
The first test fails only "sometimes" and is fixed with https://github.com/OpenSlides/openslides-backend/pull/1023. It is approved, but currently not merged.
The second test  "Check up to date models.py fails, because models.py isn't generated with current models.yml. You can generate with `make generate_models`, but you need the correct environment. One way is to call `make run-dev`. In the docker container you could call `make generate_models`.

**Comment by ostcar** [comment]
> The second test  "Check up to date models.py fails, because models.py isn't generated with current models.yml. You can generate with `make generate_models`, but you need the correct environment. One way is to call `make run-dev`. In the docker container you could call `make generate_models`.

Could you do this for me?

**Comment by r-peschke** [comment]
> > The second test  "Check up to date models.py fails, because models.py isn't generated with current models.yml. You can generate with `make generate_models`, but you need the correct environment. One way is to call `make run-dev`. In the docker container you could call `make generate_models`.
> 
> Could you do this for me?

I actualized the documentation for these steps, I think you only need Step 7, but know the other ones, too: https://github.com/OpenSlides/OpenSlides/wiki/How-to-add-a-field-to-models.yml

**Comment by ostcar** [comment]
Would it be possible for you to execute this Step for this pr?

**Comment by r-peschke** [comment]
> Would it be possible for you to execute this Step for this pr?

1.  This are 2 commands, well described, for you
2. I had to change my working branch with stash, fetch your PR, do the exactly 2 commands and then push it to your repo, with or without the right to do.

Sorry, but I think it is better that you do it yourself

**Comment by ostcar** [comment]
I could not run "make run-dev" The frist time I got a strange errors and the second time nothing happend for two miniutes:

```
make run-dev
USER_ID=$(id -u ${USER}) GROUP_ID=$(id -g ${USER}) docker-compose -f dev/docker-compose.dev.yml up --build --detach
[+] Building 4.4s (8/24)                                                                                                                                                                         
 => ERROR [openslides-auth-dev internal] load git source https://github.com/OpenSlides/openslides-auth-service.git                                                                          1.4s
 => [openslides-backend-dev internal] load build definition from Dockerfile.dev                                                                                                             0.2s
 => => transferring dockerfile: 1.11kB                                                                                                                                                      0.0s
 => [openslides-datastore-writer internal] load git source https://github.com/OpenSlides/openslides-datastore-service.git                                                                   1.5s
 => [openslides-vote-dev internal] load git source https://github.com/OpenSlides/openslides-vote-service.git#main                                                                           1.4s
 => [openslides-backend-dev internal] load .dockerignore                                                                                                                                    0.1s
 => => transferring context: 135B                                                                                                                                                           0.0s
 => [openslides-backend-dev internal] load metadata for docker.io/library/python:3.8.5-slim-buster                                                                                          1.8s
 => [openslides-backend-dev  1/17] FROM docker.io/library/python:3.8.5-slim-buster@sha256:502cd057453744145010eceb5a4af1e4f04ebed54f6e1e8d23d29ebe2afdbe6d                                  0.0s
 => ERROR [openslides-backend-dev internal] load build context                                                                                                                              0.1s
 => => transferring context:                                                                                                                                                                3.0s
------                                                                                                                                                                                           
 > [openslides-auth-dev internal] load git source https://github.com/OpenSlides/openslides-auth-service.git:                                                                                     
#1 0.305 hint: Using 'master' as the name for the initial branch. This default branch name                                                                                                       
#1 0.305 hint: is subject to change. To configure the initial branch name to use in all
#1 0.305 hint: of your new repositories, which will suppress this warning, call:
#1 0.305 hint: 
#1 0.305 hint:  git config --global init.defaultBranch <name>
#1 0.305 hint: 
#1 0.305 hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
#1 0.305 hint: 'development'. The just-created branch can be renamed via this command:
#1 0.305 hint: 
#1 0.305 hint:  git branch -m <name>
#1 0.308 Initialized empty Git repository in /var/lib/docker/btrfs/subvolumes/5hdcxs35jbspflrkjt2i2l8v8/
#1 0.879 9e252f33ccde41137a0a7174e8958d8fa3beb2f1       refs/heads/master
#1 1.207 From https://github.com/OpenSlides/openslides-auth-service
#1 1.207  * [new branch]      master     -> master
#1 1.207  * [new branch]      master     -> origin/master
------
------
 > [openslides-backend-dev internal] load build context:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3232668492/https:/github.com/OpenSlides/openslides-vote-service.git#main/Dockerfile: no such file or directory
make: *** [Makefile:77: start-dev] Fehler 17
⌁ [ossi:~/src/openslides-backend] vote_count 2 ± make run-dev
USER_ID=$(id -u ${USER}) GROUP_ID=$(id -g ${USER}) docker-compose -f dev/docker-compose.dev.yml up --build --detach
[+] Building 125.0s (2/5)                                                                                                                                                                        
 => [openslides-datastore-writer internal] load git source https://github.com/OpenSlides/openslides-datastore-service.git                                                                   1.5s
 => ERROR [openslides-auth-dev internal] load git source https://github.com/OpenSlides/openslides-auth-service.git                                                                          1.4s
------
 > [openslides-auth-dev internal] load git source https://github.com/OpenSlides/openslides-auth-service.git:
#4 -0.578 hint: Using 'master' as the name for the initial branch. This default branch name
#4 -0.578 hint: is subject to change. To configure the initial branch name to use in all
#4 -0.578 hint: of your new repositories, which will suppress this warning, call:
#4 -0.578 hint: 
#4 -0.578 hint:         git config --global init.defaultBranch <name>
#4 -0.578 hint: 
#4 -0.578 hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
#4 -0.578 hint: 'development'. The just-created branch can be renamed via this command:
#4 -0.578 hint: 
#4 -0.578 hint:         git branch -m <name>
#4 -0.575 Initialized empty Git repository in /var/lib/docker/btrfs/subvolumes/5hdcxs35jbspflrkjt2i2l8v8/
#4 -0.004 9e252f33ccde41137a0a7174e8958d8fa3beb2f1      refs/heads/master
#4 1.207 From https://github.com/OpenSlides/openslides-auth-service
#4 1.207  * [new branch]      master     -> master
#4 1.207  * [new branch]      master     -> origin/master
------
canceled
^Cmake: *** [Makefile:77: start-dev] Fehler 130
```

I don't want to deal with it any more.

I created the issue #1026 and close this pr.

**Pull request closed without merging**
