### PR TITLE
Update start_line_number default.

### PR DESCRIPTION
**Pull request by reiterl**
Update json data, add migration, update test.

### CODE REVIEW

**Review by r-peschke — COMMENTED** [review]
What is about setting the start_line_number? If the client wants to do this,this should be in motion.create/update payload!?

**Comment by reiterl** [comment]
The action to set the start_line_number is the `motion.update` action. This is already in the code.

**Review by r-peschke — APPROVED** [review]

**Comment by jsangmeister** [comment]
migration would not have been necessary since the client uses `1` as the default anyway

**Comment by r-peschke** [comment]
> migration would not have been necessary since the client uses `1` as the default anyway

Yes and no: I think the client did, the pdf-export not: IMO it's more secure to fix this with migration in the database;-)

**Pull request merged**
