### PR TITLE
Fix to KeyError of the mediafile.upload. Add test.

### PR DESCRIPTION
**Pull request by reiterl**

### CODE REVIEW

**Comment by luisa-beerboom** [comment]
Don't know if this is a leftover, but I'm getting the following error:

`Database corrupt: The resource token has to be unique, but there are 2 tokens \"None\".`

**Review by jsangmeister — CHANGES_REQUESTED** [review]
This is not the intended behaviour:
- If no token is given, the whole check in the `get_updated_instances` method can be skipped, because it must not be checked if the token is a duplicate.
- `None` is not a valid token, which should theoretically be caught by the schema, but if not, you will have to do this manually

With these changes, the errors from @luisa-beerboom should disappear.

**Comment by reiterl** [comment]
Add a test for token is None and skip the token check code, if Token is not set.

**Review by jsangmeister — APPROVED** [review]
looks good, not tested. @luisa-beerboom can you check if this fixes your problem?

**Review by luisa-beerboom — APPROVED** [review]
This fixes my problem, feel free to merge

**Pull request merged**
