### PR TITLE
Add calc fields for motion.create_forwarded.

### PR DESCRIPTION
**Pull request by reiterl**
Calc all_derived_motion_ids and all_origin_ids.
Update the tests.

**Note:** This is only the create case. The delete case must be discussed.
Based on the gen_models branch.

### CODE REVIEW

**Review by jsangmeister — CHANGES_REQUESTED** [review]
Please add more tests with more complex setups (e.g. multiple levels and/or multiple derived motions from one origin)

**Comment by reiterl** [comment]
Added a complex test to the test_create_forwarded, this shows a problem in the code. 
Fixed that too.

**Comment by jsangmeister** [comment]
waiting for a decision in #818 here

**Review by jsangmeister — APPROVED** [review]
I think this is correct for the new requirements

**Pull request merged**
