### PR TITLE
Move travis to github actions

### PR DESCRIPTION
**Pull request by jsangmeister**
Travis has to be deactivated in order to merge this.

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Does `make run-tests` executes everything: `pytest` and all format checking tools?

**Comment by jsangmeister** [comment]
> Does `make run-tests` executes everything: `pytest` and all format checking tools?

No, currently only `pytest` is executed, similar to the datastore.

**Comment by FinnStutzenstein** [comment]
> No, currently only `pytest` is executed, similar to the datastore.

I think this also should be done (after `pytest`), so `make run-tests` tests everything.

**Comment by jsangmeister** [comment]
> > No, currently only `pytest` is executed, similar to the datastore.
> 
> I think this also should be done (after `pytest`), so `make run-tests` tests everything.

Sure, can do. Should I also adjust the datastore then?

**Comment by jsangmeister** [comment]
On second thought: If you have `make run-tests` execute everything, it will terminate on the first error, which is typically not what you want in a CI, so we have to have explicit commands anyway and these are the ones getting exectuted by github actions. So when would you even use the all-in-one command?

**Comment by jsangmeister** [comment]
Merging this now; create an issue if you want `run-tests` to execute everything so we can discuss it there

**Pull request merged**
