### PR TITLE
Add auth service interface

### PR DESCRIPTION
**Pull request by jsangmeister**

### CODE REVIEW

**Comment by jsangmeister** [comment]
@FinnStutzenstein ping

**Comment by FinnStutzenstein** [comment]
Looks good, but in the meantime Gabriel did finish the real one: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/interfaces/auth-service.txt#L144

There are two functions: `toHash` generates one. `isEquals` has to be used to check, if a PW is correct, giving the user input and the hashed password

**Comment by FinnStutzenstein** [comment]
This would now add the auth service as another component to the dev/test setup. So I guess there is a bit more todo.

**Comment by jsangmeister** [comment]
Adapter implementation has to be adjusted.

**Comment by FinnStutzenstein** [comment]
Ok, the interface is bigger than needed, since login, ... are directly routed to the auth service. I think you just need authenticate, hash and isEqual. You can leave them there and delete them later, if not used.

I would prefer to merge it and see, that #120 is done. Gabriel has done more work in the library lately which is also already merged. Especially the three functions are included, so you might just need to rewrite the adapter class to convert your data representation to the library ones and convert exceptions. @jsangmeister Please ping me at thursday if you are working, so we can concentrate on getting auth-related sutff working.

**Pull request merged**
