### PR TITLE
Allow `list_of_speakers.re_add_last` for point of order speakers

### LINKED ISSUE #1951: Fix `list_of_speakers.readd_last`
see https://github.com/OpenSlides/openslides-client/issues/2991 for details on how it should work and what's broken. At least the described thrown error stems from the backend and needs to be fixed here.

### PR DESCRIPTION
**Pull request by jsangmeister**
fixes #1951

### CODE REVIEW

**Review by r-peschke — CHANGES_REQUESTED** [review]
- Please write a test for this new case and
- change the description in the wiki

**Comment by jsangmeister** [comment]
Done

**Review by Elblinator — APPROVED** [review]
function is fine

**Comment by Elblinator** [comment]
please fix coding style

**Review by r-peschke — APPROVED** [review]

**Pull request merged**
