### PR TITLE
Make meeting_user actions backend internal

### PR DESCRIPTION
**Pull request by reiterl**
First part fix  of the https://github.com/OpenSlides/openslides-backend/issues/1888

### CODE REVIEW

**Review by jsangmeister — CHANGES_REQUESTED** [review]
see https://github.com/OpenSlides/openslides-backend/issues/1888#issuecomment-1709726596

**Comment by reiterl** [comment]
meeting_user delete is backend internal. Remove most relation fields form the meeting_user create and update actions.
Remove the delegate tests, they are no longer needed.

**Comment by jsangmeister** [comment]
> meeting_user delete is backend internal

My bad, missed that

> Remove the delegate tests, they are no longer needed.

Yes they are! Move the code to `meeting_user.set_data` and the test to the according test file. Currently it seems like the relation can just be set without any checks... This should be caught by the user tests. We should check that no other such checks were broken with the template field removal.

**Review by jsangmeister — COMMENTED** [review]
Not sure about the removed permission checks in the mixin

**Review by jsangmeister — APPROVED** [review]

**Comment by reiterl** [comment]
I talked with @jsangmeister about the check_permissions. I will merge this next week.

**Pull request merged**
