### PR TITLE
Remove publish_immediately from write req. of poll and option

### PR DESCRIPTION
**Pull request by reiterl**
Publish immediately is not a poll fields. Rm it at the end of the
update_instance. Add a migration and update tests.

### CODE REVIEW

**Comment by reiterl** [comment]
This is for the first part of the issue. The check in the write requests is missing.

**Review by r-peschke — CHANGES_REQUESTED** [review]
SO far the code is okay for me. But the same happens in collection **option** with the field "publish_immediatelly". Please remove it also and write tests for it (for update you can use the option/test_update.py test_update_Y, where the field will be written to database.

**Comment by reiterl** [comment]
Also fix the publish_immediately bug in option.update. option.create doesn't need a fix.

**Review by jsangmeister — APPROVED** [review]

**Review by r-peschke — APPROVED** [review]
LGTM

**Pull request merged**
