### PR TITLE
Add applause fields to meeting.update

### PR DESCRIPTION
**Pull request by reiterl**
Add a test.

### CODE REVIEW

**Comment by reiterl** [comment]
based on the gen_model branch, because the new fields are changed in the model.

**Comment by FinnStutzenstein** [comment]
Whats the difference to #845?

**Comment by reiterl** [comment]
The difference is that there are different fields.

**Review by FinnStutzenstein — APPROVED** [review]

**Comment by FinnStutzenstein** [comment]
Please resolve conflicts.

**Pull request merged**
